version: '2'
services:
    fourbooks-app:
        image: fourbooks
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://fourbooks-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=fourbooks
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_JEST_URI=http://fourbooks-elasticsearch:9200
        ports:
            - 8080:8080
    fourbooks-mongodb:
        extends:
            file: mongodb.yml
            service: fourbooks-mongodb
    fourbooks-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fourbooks-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
